#!/bin/dash

# check direcotry .shrug
if [ -d ".shrug" ]; then
	echo "shrug-init: error: .shrug already exists"
	exit 1
fi

# check file .shrug
if [ -f ".shrug" ]; then
	echo "shrug-init: error: .shrug already exists"
	exit 1
fi

# initialise new repo
echo "Initialized empty shrug repository in .shrug"
mkdir ".shrug"
touch ".shrug/_branch"

./shrug-branch master

echo "master" > ".shrug/_branch"