#!/bin/dash

# check cwd is a repo
if [ ! -d ".shrug" ]; then
	echo "Not a repository. Call shrug-init"
	exit 1
fi

path=".shrug/$(cat .shrug/_branch)"
msg=$2

for file in $(ls $path/ | cat); do

	# only consider directories
	if [ -f $path/$file ]; then
		continue
	fi

	# changes have been STAGED for commit via shrug-add
	if [ -f $path/$file/$file ]; then
		echo "Commiting file '$file'"
		#
	else
		echo "No changes to file '$file'"
	fi
done

# commit number
n=$(wc -l $path/_commits | cut -d " " -f1)

# echo "$n:$msg" >> $path/_commits