#!/bin/dash

# check cwd is a repo
if [ ! -d ".shrug" ]; then
	# echo "Not a repository. Call shrug-init"
	exit 1
fi

path=".shrug/$(cat .shrug/_branch)"
msg=$2

if [ -z "$msg" ]; then
	msg="dummy msg"
fi


# commit number
n=$(wc -l $path/_commits | cut -d " " -f1)

found=0

for file in $(ls $path/ | cat); do

	# only consider directories
	if [ -f $path/$file ]; then
		continue
	fi

	# changes have been STAGED for commit via shrug-add
	if [ -f $path/$file/staged ]; then
		found=1
	fi
done

if [ $found -ne 0 ]; then
	echo "$n $msg" >> $path/_commits
	echo "Committed as commit $n"
        
	for file in $(ls $path/ | cat); do

                # only consider directories
                if [ -f $path/$file ]; then
                        continue
                fi

                # changes have been STAGED for commit via shrug-add

		if [ -f $path/$file/latest ]; then
			cp $path/$file/latest $path/$file/$n.$file		
		fi

                if [ -f $path/$file/staged ]; then
                        # create backup
                        cp $path/$file/staged $path/$file/$n.$file
                        mv $path/$file/staged $path/$file/latest
		fi
	done
else
	echo "nothing to commit"
fi
