#!/bin/dash

# check cwd is a repo
if [ ! -d ".shrug" ]; then
	# echo "Not a repository. Call shrug-init"
	exit 1
fi

path=".shrug/$(cat .shrug/_branch)"
msg=$2

if [ -z "$msg" ]; then
	msg="dummy msg"
fi


# commit number
n=$(wc -l $path/_commits | cut -d " " -f1)

found=0

for file in $(ls $path/ | cat); do

	# only consider directories
	if [ -f $path/$file ]; then
		continue
	fi

	# changes have been STAGED for commit via shrug-add
	if [ -f $path/$file/$file ]; then
		found=1
		# echo "Commiting file '$file'"
		# create backup
		mv $path/$file/$file $path/$file/$n.$file
	else
		# echo "No changes to file '$file'"
	fi
done

if [ $found -ne 0 ]; then
	echo "$n $msg" >> $path/_commits
	echo "Commited as commit $n"
else
	# echo "No changes to be commited"
fi